meta_product_name: "Innermile"
meta_title: "Innermile - Discover Your Local World"
meta_description: "Connect with the community from within a mile of your home"
meta_image: "cover.png"
#twitter_account: "@product_twitter_account"   # required for Twitter Cards